version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./services/gateway/nginx.config:/etc/nginx/conf.d/default.config:ro
      - ./services/gateway/html:/usr/share/nginx/html:ro
    depends_on:
      - user-api
      # - auth

  user-api:
    build:
      context: . # Use the project root as the build context
      dockerfile: ./services/user-api/Dockerfile
    container_name: user-api
    ports:
      - "8080"

  # auth:
  #   build: ./services/auth
  #   container_name: auth
  #   expose:
  #     - "8080"
